import requests

response = requests.get("https://api.census.gov/data/2021/cbp")

# print(response.status_code)
# print(response.json())

json_data = response.json()

print(json_data.keys())
print(json_data["data"])
print("-----------------")
# print(response.text)
# print("-----------------")
# print(response.dataset)
# print("-----------------")
# print(response.headers)
# print("-----------------")
# print(response.url)
# print("-----------------")
# print(response.encoding)
# print("-----------------")
# print(response.ok)
# print("-----------------")
# print(response.is_redirect)
# print("-----------------")
# print(response.is_permanent_redirect)
# print("-----------------")
# print(response.reason)
# print("-----------------")
# print(response.cookies)
